# Generated by Django 6.0.5 on 2026-05-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_project_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="recurrence",
        ),
        migrations.RemoveField(
            model_name="task",
            name="repeat_until",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="default_recurrence",
        ),
        migrations.DeleteModel(
            name="Reminder",
        ),
    ]
